wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.24.0
    framework: huggingface
    huggingface_version: 5.6.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1777231854
    t:
      1:
      - 1
      - 11
      - 49
      - 71
      2:
      - 1
      - 11
      - 49
      - 51
      - 71
      3:
      - 2
      - 4
      - 13
      - 15
      - 16
      - 42
      - 62
      4: 3.11.4
      5: 0.24.0
      6: 5.6.2
      13: linux-x86_64
    e:
      ws5oca3oa5snnlikcmvnpm9fj70cgs0e:
        os: Linux-5.14.0-611.42.1.el9_7.x86_64-x86_64-AMD_EPYC_7413_24-Core_Processor-with-glibc2.37
        python: CPython 3.11.4
        started_at: '2026-04-26T19:30:50.903627Z'
        args:
        - --model_path
        - EleutherAI/pythia-160m
        - --wandb_project
        - Stackelberg-Pythia160M
        - --wandb_group
        - Base
        - --wandb_run_name
        - Eval_testCC
        program: /lustre07/scratch/joseph63/Stackelberg-Game-Lora/pythia160M/eval.py
        code_path: pythia160M/eval.py
        code_path_local: pythia160M/eval.py
        git:
          remote_url: https://github.com/JosephdRf/Stackelberg-Game-Lora
          commit: b06e41d795eb8741e7707f3dbda1dbbe404ca5b8
        root: /lustre07/scratch/joseph63/Stackelberg-Game-Lora
        host: ng30603
        executable: /lustre07/scratch/joseph63/Stackelberg-Game-Lora/.venv/bin/python
        cpu_count: 48
        cpu_count_logical: 48
        gpu_type: NVIDIA A100-SXM4-40GB
        gpu_count: 1
        disk:
          /:
            total: '17179869184'
            used: '4892082176'
        memory:
          total: '540623351808'
        gpu_nvidia:
        - name: NVIDIA A100-SXM4-40GB
          memory_total: '42949672960'
          cuda_cores: 6912
          architecture: Ampere
          uuid: GPU-4351b05c-3005-8e2d-0477-33a0b0e86626
        cuda_version: '12.8'
        slurm:
          submit_dir: /lustre07/scratch/joseph63/Stackelberg-Game-Lora
          submit_host: narval2
          nodeid: '0'
          task_pid: '2832760'
          nodelist: ng30603
          job_uid: '3158629'
          mem_per_node: '8192'
          nnodes: '1'
          job_account: def-omar12_gpu
          job_name: game-lora-baseline
          job_end_time: '1777233506'
          script_context: prolog_task
          gtids: '0'
          procid: '0'
          topology_addr_pattern: switch.switch.node
          tres_per_task: cpu=2
          job_user: joseph63
          job_nodelist: ng30603
          cpus_on_node: '2'
          job_start_time: '1777231706'
          job_qos: normal
          tmpdir: /localscratch/joseph63.59900514.0
          conf: /etc/slurm/slurm.conf
          jobid: '59900514'
          job_cpus_per_node: '2'
          cluster_name: narval
          oom_kill_step: '0'
          mpi_type: pmix
          topology_addr: ihpc207u29.ihpc306u25.ng30603
          gpus_on_node: '1'
          restart_count: '0'
          job_num_nodes: '1'
          job_gid: '3158629'
          cpus_per_task: '2'
          job_partition: gpubase_bygpu_b1
          prio_process: '0'
          job_gpus: '3'
          job_id: '59900514'
          localid: '0'
          tasks_per_node: '1'
        writer_id: ws5oca3oa5snnlikcmvnpm9fj70cgs0e
model_path:
  desc: null
  value: EleutherAI/pythia-160m
seed:
  desc: null
  value: 42
n_samples:
  desc: null
  value: null
