wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.24.0
    framework: huggingface
    huggingface_version: 5.6.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1777337349
    t:
      1:
      - 1
      - 11
      - 49
      - 71
      2:
      - 1
      - 11
      - 49
      - 51
      - 71
      - 98
      3:
      - 2
      - 4
      - 13
      - 15
      - 16
      - 42
      - 62
      4: 3.11.4
      5: 0.24.0
      6: 5.6.2
      13: linux-x86_64
    e:
      8s0xiq3g99mn3pj1b0y5ixipdssadh1v:
        os: Linux-5.14.0-611.42.1.el9_7.x86_64-x86_64-AMD_EPYC_7413_24-Core_Processor-with-glibc2.37
        python: CPython 3.11.4
        started_at: '2026-04-28T00:49:06.414854Z'
        args:
        - --model_path
        - /lustre07/scratch/joseph63/Stackelberg-Game-Lora/checkpoints/exp1/Train_stackelberg_exp1_6/final
        - --wandb_project
        - Stackelberg-Pythia160M
        - --wandb_group
        - Exp1
        - --wandb_run_name
        - Eval_exp1_6
        program: /lustre07/scratch/joseph63/Stackelberg-Game-Lora/pythia160M/eval.py
        code_path: pythia160M/eval.py
        code_path_local: pythia160M/eval.py
        git:
          remote_url: git@github.com:JosephdRf/Stackelberg-Game-Lora.git
          commit: 1608c26f19b5a03ba9e6c55af12776bcb3a28252
        root: /lustre07/scratch/joseph63/Stackelberg-Game-Lora
        host: ng10602
        executable: /lustre07/scratch/joseph63/Stackelberg-Game-Lora/.venv/bin/python
        cpu_count: 48
        cpu_count_logical: 48
        gpu_type: NVIDIA A100-SXM4-40GB
        gpu_count: 1
        disk:
          /:
            total: '17179869184'
            used: '5041729536'
        memory:
          total: '540623355904'
        gpu_nvidia:
        - name: NVIDIA A100-SXM4-40GB
          memory_total: '42949672960'
          cuda_cores: 6912
          architecture: Ampere
          uuid: GPU-25524a47-96ac-6006-f349-8966d4bb1f6e
        cuda_version: '12.8'
        slurm:
          job_user: joseph63
          nodelist: ng10602
          tmpdir: /localscratch/joseph63.59948021.0
          procid: '0'
          task_pid: '441333'
          cpus_per_task: '10'
          job_num_nodes: '1'
          job_nodelist: ng10602
          submit_host: narval3
          script_context: prolog_task
          gtids: '0'
          job_gpus: '2'
          oom_kill_step: '0'
          job_cpus_per_node: '10'
          cluster_name: narval
          conf: /etc/slurm/slurm.conf
          mpi_type: pmix
          job_name: joseph-stackelberg-job
          job_qos: normal
          mem_per_node: '16384'
          job_id: '59948021'
          nnodes: '1'
          job_start_time: '1777332405'
          submit_dir: /lustre07/scratch/joseph63/Stackelberg-Game-Lora
          job_account: def-omar12_gpu
          tasks_per_node: '1'
          cpus_on_node: '10'
          jobid: '59948021'
          restart_count: '0'
          job_uid: '3158629'
          job_gid: '3158629'
          job_end_time: '1777343205'
          topology_addr: ihpc207u29.ihpc106u25.ng10602
          prio_process: '0'
          job_partition: gpubase_bygpu_b1
          gpus_on_node: '1'
          localid: '0'
          topology_addr_pattern: switch.switch.node
          nodeid: '0'
          tres_per_task: cpu=10
        writer_id: 8s0xiq3g99mn3pj1b0y5ixipdssadh1v
model_path:
  desc: null
  value: /lustre07/scratch/joseph63/Stackelberg-Game-Lora/checkpoints/exp1/Train_stackelberg_exp1_6/final
seed:
  desc: null
  value: 42
n_samples:
  desc: null
  value: null
