_wandb:
    value:
        cli_version: 0.25.1
        e:
            i5gx8f7msypnrgwarlq1r0grwvnq2hdt:
                args:
                    - --model_path
                    - EleutherAI/pythia-160m
                    - --csv_column
                    - base
                codePath: pythia160M/eval.py
                codePathLocal: pythia160M/eval.py
                cpu_count: 20
                cpu_count_logical: 28
                cudaVersion: "13.2"
                disk:
                    /:
                        total: "4227858432"
                        used: "1275682816"
                email: joseph.deroffignac@gmail.com
                executable: /usr/bin/python
                git:
                    commit: b1bc0df039b8de689441d8161721e46ef47cb120
                    remote: https://github.com/JosephdRf/Stackelberg-Game-Lora
                gpu: NVIDIA RTX 4000 Ada Generation
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 6144
                      memoryTotal: "21469593600"
                      name: NVIDIA RTX 4000 Ada Generation
                      uuid: GPU-4b99f32e-6ef7-75ec-c40b-15faaf717064
                host: corvette.polytechnique.fr
                memory:
                    total: "66822713344"
                os: Linux-5.14.0-611.47.1.el9_7.x86_64-x86_64-with-glibc2.34
                program: /users/eleves-a/2023/joseph.de-roffignac/stage3A/Stackelberg-Game-Lora/pythia160M/eval.py
                python: CPython 3.9.25
                root: /users/eleves-a/2023/joseph.de-roffignac/stage3A/Stackelberg-Game-Lora
                startedAt: "2026-04-17T16:25:14.871456Z"
                writerId: i5gx8f7msypnrgwarlq1r0grwvnq2hdt
        m: []
        python_version: 3.9.25
        t:
            "1":
                - 1
                - 11
                - 49
                - 71
            "2":
                - 1
                - 11
                - 49
                - 51
                - 71
            "3":
                - 2
                - 13
                - 16
            "4": 3.9.25
            "5": 0.25.1
            "6": 4.57.6
            "12": 0.25.1
            "13": linux-x86_64
model_path:
    value: EleutherAI/pythia-160m
n_samples:
    value: 2000
seeds:
    value:
        - 42
        - 43
        - 44
