wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.24.0
    framework: huggingface
    huggingface_version: 5.6.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1777231029
    t:
      1:
      - 1
      - 11
      - 49
      - 71
      2:
      - 1
      - 11
      - 49
      - 51
      - 71
      3:
      - 2
      - 4
      - 13
      - 15
      - 16
      - 42
      - 62
      4: 3.11.4
      5: 0.24.0
      6: 5.6.2
      13: linux-x86_64
    e:
      63axzeyj1r7i8vpv3qk6m46a8lcd1uba:
        os: Linux-5.14.0-611.42.1.el9_7.x86_64-x86_64-AMD_EPYC_7413_24-Core_Processor-with-glibc2.37
        python: CPython 3.11.4
        started_at: '2026-04-26T19:17:00.502575Z'
        args:
        - --model_path
        - EleutherAI/pythia-160m
        - --wandb_project
        - Stackelberg-Pythia160M
        - --wandb_group
        - Base
        - --wandb_run_name
        - Eval_testCC
        program: /lustre07/scratch/joseph63/Stackelberg-Game-Lora/pythia160M/eval.py
        code_path: pythia160M/eval.py
        code_path_local: pythia160M/eval.py
        git:
          remote_url: https://github.com/JosephdRf/Stackelberg-Game-Lora
          commit: b06e41d795eb8741e7707f3dbda1dbbe404ca5b8
        root: /lustre07/scratch/joseph63/Stackelberg-Game-Lora
        host: ng20202
        executable: /lustre07/scratch/joseph63/Stackelberg-Game-Lora/.venv/bin/python
        cpu_count: 48
        cpu_count_logical: 48
        gpu_type: NVIDIA A100-SXM4-40GB
        gpu_count: 1
        disk:
          /:
            total: '17179869184'
            used: '5038264320'
        memory:
          total: '540623360000'
        gpu_nvidia:
        - name: NVIDIA A100-SXM4-40GB
          memory_total: '42949672960'
          cuda_cores: 6912
          architecture: Ampere
          uuid: GPU-0684f6de-a4d2-d96f-8538-06942013f15d
        cuda_version: '12.8'
        slurm:
          task_pid: '312250'
          job_qos: normal
          job_nodelist: ng20202
          oom_kill_step: '0'
          submit_dir: /lustre07/scratch/joseph63/Stackelberg-Game-Lora
          job_account: def-omar12_gpu
          tres_per_task: cpu=2
          mpi_type: pmix
          job_id: '59900345'
          job_start_time: '1777230849'
          jobid: '59900345'
          cluster_name: narval
          cpus_per_task: '2'
          mem_per_node: '8192'
          job_gpus: '3'
          cpus_on_node: '2'
          job_name: game-lora-baseline
          localid: '0'
          gtids: '0'
          job_uid: '3158629'
          script_context: prolog_task
          job_end_time: '1777232649'
          conf: /etc/slurm/slurm.conf
          job_num_nodes: '1'
          topology_addr: ihpc207u29.ihpc202u25.ng20202
          restart_count: '0'
          submit_host: narval2
          job_cpus_per_node: '2'
          tasks_per_node: '1'
          nodeid: '0'
          job_partition: gpubase_bygpu_b1
          topology_addr_pattern: switch.switch.node
          gpus_on_node: '1'
          job_user: joseph63
          procid: '0'
          prio_process: '0'
          nodelist: ng20202
          job_gid: '3158629'
          nnodes: '1'
          tmpdir: /localscratch/joseph63.59900345.0
        writer_id: 63axzeyj1r7i8vpv3qk6m46a8lcd1uba
model_path:
  desc: null
  value: EleutherAI/pythia-160m
seed:
  desc: null
  value: 42
n_samples:
  desc: null
  value: null
