_wandb:
    value:
        cli_version: 0.25.1
        e:
            jp39wzi9m9kbwdsg74jg2re26dbktab4:
                args:
                    - --wandb_project
                    - Stackelberg
                    - --wandb_group
                    - baseline
                    - --run_name
                    - seed_42
                codePath: pythia160M/baseline/train_baseline.py
                codePathLocal: pythia160M/baseline/train_baseline.py
                cpu_count: 20
                cpu_count_logical: 28
                cudaVersion: "13.2"
                disk:
                    /:
                        total: "4227858432"
                        used: "1275682816"
                email: joseph.deroffignac@gmail.com
                executable: /usr/bin/python
                git:
                    commit: b1bc0df039b8de689441d8161721e46ef47cb120
                    remote: https://github.com/JosephdRf/Stackelberg-Game-Lora
                gpu: NVIDIA RTX 4000 Ada Generation
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 6144
                      memoryTotal: "21469593600"
                      name: NVIDIA RTX 4000 Ada Generation
                      uuid: GPU-4b99f32e-6ef7-75ec-c40b-15faaf717064
                host: corvette.polytechnique.fr
                memory:
                    total: "66822713344"
                os: Linux-5.14.0-611.47.1.el9_7.x86_64-x86_64-with-glibc2.34
                program: /users/eleves-a/2023/joseph.de-roffignac/stage3A/Stackelberg-Game-Lora/pythia160M/baseline/train_baseline.py
                python: CPython 3.9.25
                root: /users/eleves-a/2023/joseph.de-roffignac/stage3A/Stackelberg-Game-Lora
                startedAt: "2026-04-17T16:36:53.269614Z"
                writerId: jp39wzi9m9kbwdsg74jg2re26dbktab4
        m: []
        python_version: 3.9.25
        t:
            "1":
                - 1
                - 11
                - 49
                - 71
            "2":
                - 1
                - 11
                - 49
                - 51
                - 71
            "3":
                - 13
                - 16
            "4": 3.9.25
            "5": 0.25.1
            "6": 4.57.6
            "12": 0.25.1
            "13": linux-x86_64
batch_size_per_gpu:
    value: 8
betas:
    value:
        - 0.9
        - 0.95
dataset_config:
    value: wikitext-103-raw-v1
dataset_name:
    value: Salesforce/wikitext
dry_run:
    value: false
eval_every:
    value: 100
eval_max_batches:
    value: 50
grad_accum:
    value: 2
grad_clip:
    value: 1
log_every:
    value: 20
lr:
    value: 3e-05
model_name:
    value: EleutherAI/pythia-160m
num_workers:
    value: 2
output_dir:
    value: /users/eleves-a/2023/joseph.de-roffignac/stage3A/Stackelberg-Game-Lora/pythia160M/baseline/checkpoints
random_init:
    value: false
run_name:
    value: seed_42
save_every:
    value: 500
seed:
    value: 42
seq_len:
    value: 1024
total_tokens:
    value: 100000000
wandb_group:
    value: baseline
wandb_project:
    value: Stackelberg
warmup_ratio:
    value: 0.03
weight_decay:
    value: 0.01
